// Rosters served from /rosters.json — static file in /public
// Structure: { "2005-06": { "1": [...players], "2": [...] }, ... }
// Generated by: node scripts/fetch-rosters.mjs

let rostersData = null;
let fetchPromise = null;

async function loadRosters() {
  if (rostersData) return rostersData;
  if (!fetchPromise) {
    fetchPromise = fetch('/rosters.json')
      .then(r => { if (!r.ok) throw new Error('Failed to load rosters.json'); return r.json(); })
      .then(data => { rostersData = data; return data; });
  }
  return fetchPromise;
}

// Returns list of available seasons sorted descending
export async function getAvailableSeasons() {
  const rosters = await loadRosters();
  return Object.keys(rosters).sort((a, b) => b.localeCompare(a));
}

const teamCache = {};

export async function fetchRoster(teamId, season) {
  const key = `${season}:${teamId}`;
  if (teamCache[key]) return teamCache[key];
  try {
    const rosters = await loadRosters();
    const seasonData = rosters[season] || {};
    const players = seasonData[teamId] || [];
    teamCache[key] = players;
    return players;
  } catch (err) {
    console.error('Failed to load rosters:', err);
    return { error: 'FETCH_FAILED' };
  }
}
