// Rosters are served from /rosters.json — a static file in /public
// generated by: node scripts/fetch-rosters.mjs
// Re-run and commit whenever you want to update rosters.

let rostersData = null;
let fetchPromise = null;

async function loadRosters() {
  if (rostersData) return rostersData;
  if (!fetchPromise) {
    fetchPromise = fetch('/rosters.json')
      .then(r => { if (!r.ok) throw new Error('Failed to load rosters.json'); return r.json(); })
      .then(data => { rostersData = data; return data; });
  }
  return fetchPromise;
}

const teamCache = {};

export async function fetchRoster(teamId) {
  if (teamCache[teamId]) return teamCache[teamId];
  try {
    const rosters = await loadRosters();
    const players = rosters[teamId] || [];
    teamCache[teamId] = players;
    return players;
  } catch (err) {
    console.error('Failed to load rosters:', err);
    return { error: 'FETCH_FAILED' };
  }
}
